@startuml
skinparam classAttributeIconSize 0
class Automobile {
 -marca: string
 -modello: string
 -targa: Targa
 +Automobile(marca : string, modello : string, targa : Targa)
 +getMarca():string
 +setMarca(string)
 +getModello():string
 +setModello(string)
 +frena(): void
}

class Targa{
-numero: string
+Targa(numero : string)
+getNumero(string)
+setNumero(string)
}

Automobile "1" -- "1" Targa
@enduml